######################################################################
# @CCOSTAN - Follow Me on X
# For more info visit https://www.vcloudinfo.com/click-here
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# -------------------------------------------------------------------
# Finance - Track stock prices via Yahoo Finance.
#  Uses yahoofinance every 4 hours for TSLA, AAPL, AMZN, and MSFT.
# -------------------------------------------------------------------
# Docs: https://www.home-assistant.io/integrations/yahoofinance/
# Blog Post: https://www.vcloudinfo.com/2020/10/how-to-track-stocks-in-home-assistant-using-a-custom-component.html
######################################################################

yahoofinance:
  scan_interval:
    hours: 4
  symbols:
    - TSLA
    - AAPL
    - AMZN
    - MSFT
