######################################################################
# @CCOSTAN - Follow Me on X
# For more info visit https://www.vcloudinfo.com/click-here
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# -------------------------------------------------------------------
# Rachio Sprinkler - Rain skips and seasonal scheduling - Smart sprinkler controller via Rachio. https://amzn.to/2eoPKBW.
#  Centralizes the Rachio Sprinkler - Rain skips and seasonal scheduling package configuration and helpers.
# -------------------------------------------------------------------
######################################################################
# 
# sensor:
#   - platform: mqtt
#     state_topic: "ifttt/rachio/watering_time"
#     name: "Rachio_watering_time"

