######################################################################
# @CCOSTAN - Follow Me on X
# For more info visit https://www.vcloudinfo.com/click-here
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# -------------------------------------------------------------------
# Hidden Booleans Input Boolean Helpers - Home Assistant input boolean helpers.
#  Maintains input boolean helpers for Hidden Booleans Input Boolean Helpers.
# -------------------------------------------------------------------
######################################################################
home_stats:
  name: Home Stats
  initial: off
