######################################################################
# @CCOSTAN - Follow Me on X
# For more info visit https://www.vcloudinfo.com/click-here
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# -------------------------------------------------------------------
# Home Modes - occupancy and alert toggles for major house behaviors.
#  Guest, alert, and notification modes used by automations/scripts.
# -------------------------------------------------------------------
######################################################################

guest_mode:
  name: Guest Mode
  icon: mdi:account-alert
  initial: off

alert_mode:
  name: Alert Mode
  icon: mdi:alert-octagram
  initial: off

speech_notifications:
  name: Speech Notifications
  icon: mdi:speaker-wireless
  initial: on

text_notifications:
  name: Text Notifications
  icon: mdi:cellphone-wireless
  initial: on
