######################################################################
# @CCOSTAN - Follow Me on X
# For more info visit https://www.vcloudinfo.com/click-here
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# -------------------------------------------------------------------
# Date Time Sensor - Home Assistant sensor configuration.
#  Defines sensors for Date Time Sensor.
# -------------------------------------------------------------------
######################################################################
- platform: time_date
  display_options:
    - 'time'
    - 'date'
