######################################################################
# @CCOSTAN - Follow Me on X
# For more info visit https://www.vcloudinfo.com/click-here
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# -------------------------------------------------------------------
# Motion Group - Home Assistant entity grouping.
#  Maintains grouped entities for Motion Group.
# -------------------------------------------------------------------
######################################################################
motion:
  name: Motion Detectors
  entities:
    - binary_sensor.office_motion
    

