######################################################################
# @CCOSTAN - Follow Me on X
# For more info visit https://www.vcloudinfo.com/click-here
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# -------------------------------------------------------------------
# People Group - Home Assistant entity grouping.
#  Maintains grouped entities for People Group.
# -------------------------------------------------------------------
######################################################################
family:
  entities:
    - person.carlo
    - person.stacey
    - person.justin
    - person.paige


arriving:
  name: Arriving
  entities: []
