######################################################################
# @CCOSTAN - Follow Me on X
# For more info visit https://www.vcloudinfo.com/click-here
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# -------------------------------------------------------------------
# Script to shut switches with a 30 second delay to not trample codes - Sample Call.
#  Defines the Script to shut switches with a 30 second delay to not trample codes sequence for reuse by automations and dashboards.
# -------------------------------------------------------------------
# Notes: Example action call was documented in the legacy header
# Notes: - service: script.interior_off
######################################################################
interior_off:
  sequence:
    - service: homeassistant.turn_off
      entity_id:
        - group.interior_lights
        - group.interior_switches
        - switch.lr_amp
        - group.tvs
    - service: script.paige_lights_off  # C by GE Lights  (https://amzn.to/30w3UWy)
#    - service: script.noon_lights_off   # Noon Home Smart Lights (https://amzn.to/3fOIPx6)
